name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Set up JDK 17
      uses: actions/setup-java@v3.13.0
      with:
        java-version: '17'
        distribution: 'oracle'
        
    - name: Build with Gradle
      env:
        DB_NAME: ${{ secrets.DB_NAME }}
        HMAC512_SECRET: ${{ secrets.HMAC512_SECRET }}
        MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
        MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
        MYSQL_USERNAME: ${{ secrets.MYSQL_USERNAME }}
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
      with:
        arguments: build
        
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag deploy_prod:$(date +%s)
